services:
  mongodb:
    image: mongo:7
    container_name: mongodb
    ports:
      - "27017:27017"

  notes:
    build: .
    image: notes-image
    container_name: notes-app
    depends_on:
      - mongodb
    environment:
      MONGODB_URI: ${MONGODB_URI}
    ports:
      - "8000:8000"
